# hostname (and path) to the root
baseURL: "https://leanweb.dev"

# Customer parameters
params:
  description: "How to build a simpler, faster world-wide web."
  api: "https://gomakethings.com/api/data.json"
  rssURL: ""
  rssLimit: 7
  minify: true
  css:
    - fonts.css
    - _config.css
    - reset.css
    - grid.css
    - typography.css
    - code.css
    - chroma.css
    - buttons.css
    - forms.css
    - form-validation.css
    - images.css
    - icons.css
    - fluidvids.css
    - callouts.css
    - tables.css
    - nav-main.css
    - nav-secondary.css
    - utilities.css
    - print.css

# Caches
caches:
  getjson:
    maxAge: "10m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "The Lean Web"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

# Permalinks
# See "content-management/permalinks"
permalinks:
  ebook: /:section/:title/

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true