# hostname (and path) to the root
baseURL: "https://leanweb.dev"

# Customer parameters
params:
  description: "How to build a simpler, faster world-wide web."
  api: "https://gomakethings.com/api/data.json"
  font: "https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i&display=swap"
  rssURL: ""
  rssLimit: 7
  minify: true

# Caches
caches:
  getjson:
    maxAge: "10m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "The Lean Web"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

# Permalinks
# See "content-management/permalinks"
permalinks:
  ebook: /:section/:title/

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true